name: Checkin

on:
    workflow_dispatch:
    schedule:
        - cron: '30 9,23 * * *'
    watch:
        types: 
            - started

env:
    TZ: Asia/Shanghai
    USERS: ${{secrets.USERS}}
    PUSH_KEY: ${{secrets.PUSH_KEY}}
    domain0: ${{secrets.domain0}}
    domain1: ${{secrets.domain1}}
    domain2: ${{secrets.domain2}}



jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            
            - name: Install depends
              run: |
                sudo apt-get update
                sudo apt-get -y install curl jq

            - name: Request API
              run: |
                bash test.sh
